version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: estudonext
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: estudonext
    ports:
      - "3060:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
